
export PATH="/Applications/Sublime Text 2.app/Contents/SharedSupport/bin/:$PATH"
export EDITOR=subl

source ~/.gitprompt
source ~/.bashrc
alias gst="git status"
alias md="cd ~/Projects/mdlive/legacy/"
alias st="cd ~/Projects/mdlive/stern/"
alias fr="cd ~/Projects/mdlive/fore/"
alias pp="cd ~/Projects/mdlive/port/"
alias ga="git add"
alias gc="git commit -m"
alias gd="git diff"
alias gp="git push"
alias gpo="git push origin"
alias gpom="git push origin master"
alias gpl="git pull"
alias gmm="git merge master"
alias gm="git merge"
alias gk="gitk"
alias gb="git branch"
alias gco="git checkout"
alias sb="subl"
alias sbm="subl ~/Projects/mdlive/legacy/"
alias sbs="subl ~/Projects/mdlive/stern/"
alias sbf="subl ~/Projects/mdlive/fore/"
alias sbb="subl ~/Projects/breakthrough"
alias sbp="subl ~/Projects/mdlive/port/"
alias sba="subl ~/Projects/mdlive/api-testing/"
alias gcom="git checkout master"
alias glol="git log --oneline --graph --all --decorate"
alias gka="gitk --all"
alias gl="git log"
alias gs="git stash"
alias gsp="git stash pop"
alias sbsl="subl ~/Projects/mdlive/sloop/"
alias sl="cd ~/Projects/mdlive/sloop/"
alias ap="cd ~/Projects/mdlive/api-testing/"
alias nx="sudo nginx"
alias nxs="sudo nginx -s stop"
alias vst="vim ~/Projects/mdlive/stern/"
alias vmd="vim ~/Projects/mdlive/legacy/"
