export PATH=$PATH:/Applications/Postgres.app/Contents/Versions/9.4/bin

#source ~/.gitprompt

alias p2p="cd code/places2play/"
alias ngrok="~/ngrok"
alias mvim="/Applications/MacVim.app/Contents/MacOS/Vim -g"
alias gst="git status"
alias ga="git add"
alias gc="git commit -m"
alias gco="git checkout"
alias gp="git push"
alias gpom="git push origin master"
alias gphm="git push heroku master"
alias gpem="git push origin master; git push heroku master"
alias gpl="git pull"
alias gx="gitx"
alias st="open -a SourceTree ./"
alias gb="git branch"
alias sb="open /Applications/Sublime\ Text.app"
alias glol="git log --oneline --graph --all --decorate"
alias gll='git log --graph --pretty=format:"%Cred%h%Creset -%C(yellow)%d%Creset %s %Cgreen(%cr) %C(bold blue)<%an>%Creset" --abbrev-commit'
alias gd="git diff"
alias gdc="git diff --cached"
alias gpo="git push origin"
alias gl="git log"
alias gm="git merge"
alias gmm="git merge master"
alias gs="git stash"
alias gsp="git stash pop"
alias gcom="git checkout master"
alias v="mvim"
alias mu="mysql -uroot"
alias ct="ctags -R --exclude=.git --exclude=log *"
alias c="rails c"
alias rs="rails s"
alias grh="git reset HEAD"
alias grs="git restore --staged"
alias ctags="`brew --prefix`/bin/ctags"
alias b="bundle"
alias be="bundle exec"
alias g="guard"
alias f="fg"
alias ..="cd .."
